{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/outils\/errormessage\/message"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/Outils\/documentation\/Outils\/ErrorMessage\/message","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The error message"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"message","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6Outils12ErrorMessageV7messageSSvp","modules":[{"name":"Outils"}]},"hierarchy":{"paths":[["doc:\/\/Outils\/documentation\/Outils","doc:\/\/Outils\/documentation\/Outils\/ErrorMessage"]]},"seeAlsoSections":[{"title":"API","identifiers":["doc:\/\/Outils\/documentation\/Outils\/ErrorMessage\/callSite-swift.property"],"generated":true}],"references":{"doc://Outils/documentation/Outils/ErrorMessage/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The error message"}],"identifier":"doc:\/\/Outils\/documentation\/Outils\/ErrorMessage\/message","kind":"symbol","type":"topic","url":"\/documentation\/outils\/errormessage\/message"},"doc://Outils/documentation/Outils/ErrorMessage/callSite-swift.property":{"role":"symbol","title":"callSite","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"callSite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorMessage","preciseIdentifier":"s:6Outils12ErrorMessageV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CallSite","preciseIdentifier":"s:6Outils12ErrorMessageV8CallSiteV"}],"abstract":[{"type":"text","text":"The call site where the error occured"}],"identifier":"doc:\/\/Outils\/documentation\/Outils\/ErrorMessage\/callSite-swift.property","kind":"symbol","type":"topic","url":"\/documentation\/outils\/errormessage\/callsite-swift.property"},"doc://Outils/documentation/Outils/ErrorMessage":{"role":"symbol","title":"ErrorMessage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorMessage"}],"abstract":[{"type":"text","text":"A reusable swift error struct"}],"identifier":"doc:\/\/Outils\/documentation\/Outils\/ErrorMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorMessage"}],"url":"\/documentation\/outils\/errormessage"},"doc://Outils/documentation/Outils":{"role":"collection","title":"Outils","abstract":[],"identifier":"doc:\/\/Outils\/documentation\/Outils","kind":"symbol","type":"topic","url":"\/documentation\/outils"}}}